# Generated by Django 4.1.3 on 2022-11-17 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.CharField(default='', max_length=228),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[('RECORDS', 'Records'), ('CLOTHES', 'Clothing'), ('POSTERS', 'Posters'), ('FURNITU', 'Furniture'), ('VARIOUS', 'Various')], default='VARIOUS', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='year',
            field=models.PositiveIntegerField(default='2022', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)]),
            preserve_default=False,
        ),
    ]
