# Generated by Django 4.1.3 on 2022-11-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_offer_description_offer_type_offer_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[('RECORDS', 'Records'), ('CLOTHES', 'Clothing'), ('POSTERS', 'Posters'), ('FURNITU', 'Furniture'), ('MISC', 'Miscellaneous')], max_length=7),
        ),
    ]
