# Generated by Django 4.1.3 on 2022-11-17 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_offer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
    ]
