# Generated by Django 4.1.3 on 2022-11-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_remove_band_like_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('ROCK', 'Rock'), ('RAP', 'Rap'), ('HH', 'Hip Hop'), ('SP', 'Synth Pop'), ('AR', 'Alternative Rock'), ('METAL', 'Metal')], max_length=5),
        ),
    ]
